# Codeship specific docker compose file for module tester

version: "2"

services:

  app:
    image: pwcsexperiencecenter/drupal-module-tester:latest
    cached: true
    links:
      - dmtdb
    ports:
      - "8000"
    environment:
      - TEST_MODULE=elastic_search
    volumes:
      - ./:/opt/app-root/test

  dmtdb:
    image: mariadb:latest
    cached: true
    ports:
      - "3306" # Map this dynamically on the ci, as parallel builds require it
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=site
      - MYSQL_USER=dbuser
      - MYSQL_PASSWORD=dbpass