# Local development environment for the elastic_search plugin

version: "2"

services:

  app:
    image: pwcsexperiencecenter/drupal-module-tester:latest
    entrypoint: /opt/app-root/scripts/debug.sh
    links:
      - dmtdb
    ports:
      - "8000:8000"
    environment:
      - TEST_MODULE=elastic_search
      - BOOTSTRAP=true
      - DRUPAL_ACCOUNT_PASS="p4$$"
    volumes:
      - ./:/opt/app-root/test

  #DB service must be named dmtdb locally
  dmtdb:
    image: mariadb:latest
    ports:
      - "3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=site
      - MYSQL_USER=dbuser
      - MYSQL_PASSWORD=dbpass