# Local development environment for the elastic_search plugin

version: "2"

services:

  app:
    image: pwcsexperiencecenter/drupal-module-tester:latest
    entrypoint: /opt/app-root/test/dev/start.sh
    links:
      - dmtdb
    ports:
      - "8000:8000"
    environment:
      - TEST_MODULE=elastic_search
      # BOOTSTRAP=true installs Drupal and the TEST_MODULE on container start
      - BOOTSTRAP=true
      # Uncomment this line to stop the default config for local server settings being used on install
      # You will need to manually set your own or alternatively leave this line in and link a different file to
      # /opt/app-root/test/dev/elastic_search.server.yml
#      - DEFAULT_CONFIG=false
      - DRUPAL_ACCOUNT_PASS=changeme
    volumes:
      - ./../:/opt/app-root/test

  #DB service must be named dmtdb locally
  dmtdb:
    image: mariadb:latest
    ports:
      - "3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=site
      - MYSQL_USER=dbuser
      - MYSQL_PASSWORD=dbpass
# Uncomment for db persistence, you may need to configure your folder so that mariadb can chown it's contents successfully
#    volumes:
#      - ./db:/var/lib/mysql

  elasticsearch:
      image: docker.elastic.co/elasticsearch/elasticsearch:5.4.0
      container_name: elasticsearch
      environment:
        - cluster.name=d8-elastic-module-cluster
        - bootstrap.memory_lock=true
        - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      ulimits:
        memlock:
          soft: -1
          hard: -1
      mem_limit: 1g
# Uncomment for elastic persistence
#      volumes:
#        - ./esdata:/usr/share/elasticsearch/data
      ports:
        - 9200:9200

  kibana:
    image: docker.elastic.co/kibana/kibana:5.4.0
    links:
      - elasticsearch
    ports:
      - 5601:5601
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
