auth:
  password: changeme
  username: elastic
scheme: http
host: elasticsearch
port: '9200'
kibana: ''
index_prefix: ''
advanced:
  pause: 0
  batch_size: 100
  index_batch_size: 1
  queue_update: true
  queue_insert: false
  queue_delete: true
  active: 0
  developer:
    active: true
    logging_channel: elastic.logger
  validate:
    active: 1
    die_hard: 0