elastic_search.elastic_index.*:
  type: config_entity
  label: 'Elastic index config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    uuid:
      type: string
    indexId:
      type: string
      label: 'Index Name'
    indexLanguage:
      type: string
      label: 'Index Language'
    separator:
      type: string
      label: 'Separator'
    needsUpdate:
      type: bool
    mappingEntityId:
      type: string