elastic_search.server:
  type: config_object
  mapping:
    host:
      type: string
    scheme:
      type: string
    port:
      type: string
    auth:
      type: mapping
      mapping:
        username:
          type: string
        password:
          type: string
    kibana:
      type: string
    index_prefix:
      type: string
    advanced:
      type: mapping
      mapping:
        pause:
          type: integer
        batch_size:
          type: integer
        index_batch_size:
          type: integer
        queue_update:
          type: boolean
        queue_insert:
          type: boolean
        queue_delete:
          type: boolean
        active:
          type: boolean
        developer:
          type: mapping
          mapping:
            active:
              type: boolean
            logging_channel:
              type: string
        validate:
          type: mapping
          mapping:
            active:
              type: boolean
            die_hard:
              type: boolean





#auth:
#  password: OBhpK1vUXDOhMNRbfj9ueKUg
#  username: elastic
#scheme: https
#host: 96d8d264bd451a2b4552b77eccf0634b.eu-west-1.aws.found.io
#port: '9243'
#kibana: 'https://bd38e68d47dda14713302b62819fbc41.eu-west-1.aws.found.io'
#advanced:
#  active: 1
#  developer:
#    active: 1
#    logging_channel: elastic.logger
#  validate:
#    active: 0
#    die_hard: 1
