elastic_search.elastic_analyzer.*:
  type: config_entity
  label: 'Elastic analyzer config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    uuid:
      type: string
    analyzer:
      type: string
      label: 'Analyzer'
    internal:
      type: boolean
      Label: 'Internal'
