elastic_search.fieldable_entity_map.*:
  type: config_entity
  label: 'Fieldable entity map config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    uuid:
      type: string
      label: 'uuid'
    active:
      type: boolean
      label: 'active'
    childOnly:
       type: boolean
       label: 'child only'
    recursionDepth:
      type: integer
      label: 'recursion depth'
    simpleReference:
      type: boolean
      label: 'simple reference'
    dynamicMapping:
      type: boolean
      label: 'dynamic mapping'
    fields:
      type: elastic_search.fieldable_entity.fields
      label: 'fields'


elastic_search.fieldable_entity.fields:
  type: sequence
  sequence:
    type: mapping
    mapping:
      nested:
        type: string
        label: 'Nested'
      map:
        type: sequence
        sequence:
          type: mapping
          mapping:
            type:
              type: string
            options:
              type: sequence
              sequence:
                type: ignore
            identifier:
              type: string
            target_type:
              type: string
            target_bundle:
              type: string
            field_data:
              type: elastic_search.fieldable_entity.fields

elastic_search.fieldableentitymapgeneration:
  type: config_object
  mapping:
    elastic_search:
      type: string
